Repository wecode-bootcamp-korea/44-backend-westagram-1, pull requests merged in 2023-03, with the labels that each got.

#8 [44기 송석준] 초기환경 세팅
  song/.env.sample
  song/.gitignore
  song/app.js
  song/package-lock.json
  song/package.json
Labels: 완료

#11 [김민서] Assignment -1 초기세팅
  minseo/.env.sample
  minseo/.gitignore
  minseo/app.js
  minseo/package-lock.json
  minseo/package.json
Labels: 완료

#15 [김원종] Assignment1 Express 초기 환경 세팅
  wonjong/.envsample
  wonjong/.gitignore
  wonjong/app.js
  wonjong/package-lock.json
  wonjong/package.json
Labels: 리뷰 진행 중

#13 [김민서] Assignment 2 회원가입
  minseo/.gitignore
  minseo/app.js
  minseo/db/migrations/20230322125429_create_users_table.sql
Labels: 리뷰 진행 중

#9 [김원종] Assignment 2: Express API - 유저 회원가입 하기
  wonjong/app.js
  wonjong/db/migrations/20230323042012_create_westagram2_users_table.sql
  wonjong/db/migrations/20230323042020_create_westagram2_posts_table.sql
  wonjong/db/migrations/20230323042026_create_westagram2_likes_table.sql
Labels: 멘토 리뷰 요청

#16 [김민서][ADD]Assignment 3
  minseo/app.js
  minseo/db/migrations/20230323042625_create_posts_table.sql
Labels: 리뷰 진행 중

#12 [송석준] Assignment 2: Express API - 유저 회원가입 하기
  song/.gitignore
  song/app.js
  song/db/migrations/20230322022430_create_users_table.sql.sql
  song/db/migrations/20230322023806_create_posts_table.sql.sql
  song/db/migrations/20230322040634_create_likes_table.sql.sql
  song/db/migrations/20230322041011_create_comments_table.sql.sql
Labels: 리뷰 진행 중

#17 [김원종][ADD]Assignment3 -게시글등록, 조회,유저의 게시글 조회
  wonjong/app.js
Labels: 멘토 리뷰 요청

#18 [김민서][ADD]Assignment 4
  minseo/.gitignore
  minseo/app.js
  minseo/db/migrations/20230323051318_create_likes_table.sql
  minseo/makeModules.js
Labels: 완료

#19 [김원종][ADD] Assignment-6,7,8 게시글수정,삭제하기 좋아요누르기
  wonjong/.gitignore
  wonjong/app.js
Labels: 완료

#21 [박세익]Assignment 3, 4, 5 - 3개 미션
  seyik/app.js
Labels: 완료

#20 [송석준] Assignment 3, 4, 5: Express API - CRUD(1)
  song/.env.sample
  song/.gitignore
  song/app.js
  song/db/migrations/20230322023806_create_posts_table.sql.sql
  song/db/migrations/20230322040634_create_likes_table.sql.sql
Labels: 완료

#22 [송석준] Assignment 6, 7, 8: Express API - CRUD(2)
  song/app.js
Labels: 멘토 리뷰 요청

#23 [박세익]Assignment 6, 7, 8 - 3개 미션
  seyik/.gitignore
  seyik/app.js
Labels: 멘토 리뷰 요청

#25 [김원종][ADD]Feature/wonjong layered pattern
  wonjong/.envsample
  wonjong/.eslintrc.yml
  wonjong/.gitignore
  wonjong/app.js
  wonjong/controllers/likeController.js
  wonjong/controllers/postController.js
  wonjong/controllers/userController.js
  wonjong/db/migrations/20230325060311_create_westagram_new_users_table.sql
  wonjong/db/migrations/20230325060316_create_westagram_new_posts_table.sql
  wonjong/db/migrations/20230325060322_create_westagram_new_likes_table.sql
  wonjong/models/appDataSource.js
  wonjong/models/likeDao.js
  wonjong/models/postDao.js
  wonjong/models/userDao.js
  wonjong/routes/index.js
  wonjong/routes/likeRouter.js
  wonjong/routes/postRouter.js
  wonjong/routes/userRouter.js
  wonjong/services/likeService.js
  wonjong/services/postService.js
  wonjong/services/userService.js
Labels: 완료

#24 [김민서][ADD]Feature/minseo layered pattern
  minseo/.gitignore
  minseo/.prettierrc
  minseo/app.js
  minseo/controller/likesController.js
  minseo/controller/postController.js
  minseo/controller/userController.js
  minseo/db/migrations/20230327072746_modify_usersANDposts_table.sql
  minseo/makeModules.js
  minseo/models/appDataSource.js
  minseo/models/likesDao.js
  minseo/models/postDao.js
  minseo/models/userDao.js
  minseo/routers/index.js
  minseo/routers/likesRouter.js
  minseo/routers/postRouter.js
  minseo/routers/userRouter.js
  minseo/service/likesService.js
  minseo/service/postService.js
  minseo/service/userService.js
Labels: 완료

#29 [송석준]Feature/song assignment layered pattern
  song/app.js
  song/controllers/likeController.js
  song/controllers/postController.js
  song/controllers/userController.js
  song/models/appDataSource.js
  song/models/likeDao.js
  song/models/postDao.js
  song/models/userDao.js
  song/routers/index.js
  song/routers/likeRouter.js
  song/routers/postRouter.js
  song/routers/userRouter.js
  song/services/likeService.js
  song/services/postService.js
  song/services/userService.js
Labels: 멘토 리뷰 요청

#30 [김민서][ADD] jwtToken
  minseo/controller/likesController.js
  minseo/controller/postController.js
  minseo/controller/userController.js
  minseo/db/migrations/20230329124245_modify_userEmail_table.sql
  minseo/middleware/auth.js
  minseo/models/postDao.js
  minseo/models/userDao.js
  minseo/package-lock.json
  minseo/package.json
  minseo/routers/postRouter.js
  minseo/routers/userRouter.js
  minseo/service/likesService.js
  minseo/service/postService.js
  minseo/service/userService.js
Labels: 완료
